name: Generate communities.json

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: github.repository == 'discord/discord-open-source'
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
      if: github.repository == 'discord/discord-open-source'
    - name: Update communities.json
      run: node join.js
      if: github.repository == 'discord/discord-open-source'
    - name: Update git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        (git add . && git commit -m "Update communities.json" && git push) || :
      if: github.repository == 'discord/discord-open-source'